on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-mac:
    # TODO: if new version then run this
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13

      - uses: actions/checkout@v1
      - run: g++ -o Tests/output -std=c++17 Tests/index.cpp && ./Tests/output

      - working-directory: ./mac
        id: xcodebuildStep
        run: |
          xcodebuild -target KeyRemapperTerminal archive -configuration Release
          echo "::set-output name=appBinPath::$(echo $(dirname $(readlink mac/build/Release/KeyRemapperTerminal)))"

      - uses: actions/upload-artifact@v3
        with:
          name: macArtifact
          path: |
            ${{ steps.xcodebuildStep.outputs.appBinPath }}/**/*





  release:
    runs-on: ubuntu-latest
    needs: [build-mac]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: macArtifact
          path: macArtifact
          retention-days: 1

      - run: cp macArtifact mac
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            mac
