on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-mac:
    # TODO: if new version then run this
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13

      - uses: actions/checkout@v1
      - run: g++ -o Tests/output -std=c++17 Tests/index.cpp && ./Tests/output

      - working-directory: ./mac
        id: xcodebuildStep
        run: |
          xcodebuild -target KeyRemapperTerminal archive -configuration Release

          # Get the dirpath of the executable
          binPath=$(echo $(dirname $(readlink "build/Release/KeyRemapperTerminal")))

          rm -rf output
          mkdir output
          cp -r "$binPath" output/mac
          cd output
          zip -r mac.zip mac

      - uses: actions/upload-artifact@v3
        with:
          name: macArtifact
          retention-days: 1
          path: |
            mac/output/mac.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-mac]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: macArtifact
          path: buildMac

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            buildMac/mac.zip
