on:
  push:
    branches:
      - master

jobs:
  build-mac:
    # TODO: if new version then run this
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13
      - uses: actions/checkout@v1
      - run: echo YIKES
      - run: echo YIKES2
      - run: g++ -o Tests/output -std=c++17 Tests/index.cpp && ./Tests/output
      - run: echo YIKES3
      - working-directory: ./mac
        run: xcodebuild -target KeyRemapperTerminal archive -configuration Release
      - run: echo YIKES4

      # copy this to the release folder
      # - run: cp build/Release/KeyRemapperTerminal
