on:
  push:
    branches:
      - master
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-mac:
    # TODO: if new version then run this
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13

      - uses: actions/checkout@v1
      - run: g++ -o Tests/output -std=c++17 Tests/index.cpp && ./Tests/output

      - working-directory: ./mac
        run: xcodebuild -target KeyRemapperTerminal archive -configuration Release

      - name: Move app for mac to root folder
      - run: mv build/Release/KeyRemapperTerminal KeyRemapper

      - name: Release
        uses: softprops/action-gh-release@v1
        # NO NEEDED IT SEEMS
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: KeyRemapper
