on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-mac:
    # TODO: if new version then run this
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13

      - uses: actions/checkout@v1
      - run: g++ -o Tests/output -std=c++17 Tests/index.cpp && ./Tests/output

      - working-directory: ./mac
        id: xcodebuildStep
        run: |
          xcodebuild -target KeyRemapperTerminal archive -configuration Release

          binPath=$(echo $(dirname $(readlink build/Release/KeyRemapperTerminal)))

          cp -R $binPath ../macApp

      - uses: actions/upload-artifact@v3
        # echo "::set-output name=appBinPath::$(echo $(dirname $(readlink mac/build/Release/KeyRemapperTerminal)))"
        with:
          name: macArtifact
          retention-days: 1
          path: |
            macApp/**/*

  release:
    runs-on: ubuntu-latest
    needs: [build-mac]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: KeyRemapperMac
          path: macArtifact

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            KeyRemapperMac/**/*
